/******************************************************************************* 
** Magnus MAGNUX Cpp source code 
** (c) Copyright 2011-2018 Magnus siiftun1857 Frankline 
** This creation is licensed under Apache License Version 2.0 
** For more information, see LICENSE and README.MD 
**  
** Filename: siiftun1857/magnux-core/MAGNUX_LIBCRE.cpp 
** Author: Magnus siiftun1857 Frankline 
** Date: 2018-11-18 13:59:59 
** 
*/
#include "MAGNUX_LIBCRE.h"

namespace magnux
{
	
}//end namespace magnux 

/* eof MAGNUX_LIBCRE.cpp */
