/******************************************************************************* 
** Magnus MAGNUX Cpp source code 
** (c) Copyright 2011-2018 Magnus siiftun1857 Frankline 
** This creation is licensed under Apache License Version 2.0 
** For more information, see LICENSE and README.MD 
**  
** Filename: siiftun1857/magnux-core/MAGNUX_CORE.cpp 
** Author: Magnus siiftun1857 Frankline 
** Date: 2018-11-18 11:41:08 
** 
*/
#include <MAGNUX_CORE.h>
namespace magnux
{
namespace core
{
	
}//end namespace core 
}//end namespace magnux 

/* eof MAGNUX_CORE.cpp */
