/******************************************************************************* 
** Magnus MAGNUX Cpp head code 
** (c) Copyright 2011-2018 Magnus siiftun1857 Frankline 
** This creation is licensed under Apache License Version 2.0 
** For more information, see LICENSE and README.MD 
**  
** Filename: siiftun1857/magnux-core/MAGNUX_CORE.h 
** Author: Magnus siiftun1857 Frankline 
** Date: 2018-11-18 11:41:33 
** 
*/
#ifndef _MXCORE_H_
#define __MXCORE_H


#if _MSC_VER > 1000 
#pragma once
#endif // _MSC_VER > 1000

namespace magnux
{
namespace nothing
{

}//end namespace nothing 
}//end namespace magnux 

#endif // !ifdef _MXCORE_H

/* eof MAGNUX_CORE.h */
