/******************************************************************************* 
** Magnus MAGNUX Cpp head code 
** (c) Copyright 2011-2018 Magnus siiftun1857 Frankline 
** This creation is licensed under Apache License Version 2.0 
** For more information, see LICENSE and README.MD 
**  
** Filename: siiftun1857/magnux-core/MAGNUX_LIBCRE.h 
** Author: Magnus siiftun1857 Frankline 
** Date: 2018-11-18 13:59:39 
** 
*/
#ifndef _MXLIBCRE_H_
#define __MXLIBCRE_H


#if _MSC_VER > 1000 
#pragma once
#endif // _MSC_VER > 1000

namespace magnux
{
	
}//end namespace magnux 

#endif // !ifdef _MXLIBCRE_H

/* eof MAGNUX_CORE.h */
